<a href="https://colab.research.google.com/github/Hansika-Gupta/Mobile-phone-Price-Prediction/blob/main/Mobile_Price_Prediction_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import ast

In [ ]:
dataset=pd.read_csv("/content/mobiLe data Finale5 - Mobile phone price (2).csv")
dataset

Brand              Model Storage123 RAM123  Screen Size (inches)  \
0      Apple      iPhone 13 Pro     128 GB   6 GB                  6.10   
1    Samsung   Galaxy S21 Ultra     256 GB  12 GB                  6.80   
2    OnePlus              9 Pro     128 GB   8 GB                  6.70   
3     Xiaomi  Redmi Note 10 Pro     128 GB   6 GB                  6.67   
4     Google            Pixel 6     128 GB   8 GB                  6.40   
..       ...                ...        ...    ...                   ...   
402  Samsung   Galaxy Note20 5G        128      8                  6.70   
403   Xiaomi      Mi 10 Lite 5G        128      6                  6.57   
404    Apple  iPhone 12 Pro Max        128      6                  6.70   
405     Oppo              Reno3        128      8                  6.40   
406  Samsung    Galaxy S10 Lite        128      6                  6.70   

            Camera (MP)  Battery Capacity (mAh) Price ($)123 Storage1  Rows  \
0          12 + 12 + 12                    3095          999   128 GB     2   
1    108 + 10 + 10 + 12                    5000         1199   256 GB     3   
2       48 + 50 + 8 + 2                    4500          899   128 GB     4   
3        64 + 8 + 5 + 2                    5020          279   128 GB     5   
4             50 + 12.2                    4614          799   128 GB     6   
..                  ...                     ...          ...      ...   ...   
402            12+64+12                    4300         1049    128GB   404   
403            48+8+2+2                    4160          349    128GB   405   
404            12+12+12                    3687         1099    128GB   406   
405           48+13+8+2                    4025          429    128GB   407   
406             48+12+5                    4500          649    128GB   408   

     Storage   RAM1  rows  RAM  Row  Price($)  
0        128   6 GB     2    6    2       999  
1        256  12 GB     3   12    3      1199  
2        128   8 GB     4    8    4       899  
3        128   6 GB     5    6    5       279  
4        128   8 GB     6    8    6       799  
..       ...    ...   ...  ...  ...       ...  
402      128    8GB   404    8  404      1049  
403      128    6GB   405    6  405       349  
404      128    6GB   406    6  406      1099  
405      128    8GB   407    8  407       429  
406      128    6GB   408    6  408       649  

[407 rows x 16 columns]

In [ ]:
dataset.head()

Brand              Model Storage123 RAM123  Screen Size (inches)  \
0    Apple      iPhone 13 Pro     128 GB   6 GB                  6.10   
1  Samsung   Galaxy S21 Ultra     256 GB  12 GB                  6.80   
2  OnePlus              9 Pro     128 GB   8 GB                  6.70   
3   Xiaomi  Redmi Note 10 Pro     128 GB   6 GB                  6.67   
4   Google            Pixel 6     128 GB   8 GB                  6.40   

          Camera (MP)  Battery Capacity (mAh) Price ($)123 Storage1  Rows  \
0        12 + 12 + 12                    3095          999   128 GB     2   
1  108 + 10 + 10 + 12                    5000         1199   256 GB     3   
2     48 + 50 + 8 + 2                    4500          899   128 GB     4   
3      64 + 8 + 5 + 2                    5020          279   128 GB     5   
4           50 + 12.2                    4614          799   128 GB     6   

   Storage   RAM1  rows  RAM  Row  Price($)  
0      128   6 GB     2    6    2       999  
1      256  12 GB     3   12    3      1199  
2      128   8 GB     4    8    4       899  
3      128   6 GB     5    6    5       279  
4      128   8 GB     6    8    6       799

In [ ]:
dataset.isnull().sum()

Brand                     0
Model                     0
Storage123                0
RAM123                    0
Screen Size (inches)      0
Camera (MP)               0
Battery Capacity (mAh)    0
Price ($)123              0
Storage1                  0
Rows                      0
Storage                   0
RAM1                      0
rows                      0
RAM                       0
Row                       0
Price($)                  0
dtype: int64

In [ ]:
print(dataset.columns)

Index(['Brand', 'Model', 'Storage123', 'RAM123', 'Screen Size (inches)',
       'Camera (MP)', 'Battery Capacity (mAh)', 'Price ($)123', 'Storage1',
       'Rows', 'Storage', 'RAM1', 'rows', 'RAM', 'Row', 'Price($)'],
      dtype='object')


In [ ]:
dataset.drop(['Model','Storage123','RAM123','Price ($)123','Storage1','Rows','RAM1','rows','Row'],axis=1,inplace=True)
dataset

Brand  Screen Size (inches)         Camera (MP)  \
0      Apple                  6.10        12 + 12 + 12   
1    Samsung                  6.80  108 + 10 + 10 + 12   
2    OnePlus                  6.70     48 + 50 + 8 + 2   
3     Xiaomi                  6.67      64 + 8 + 5 + 2   
4     Google                  6.40           50 + 12.2   
..       ...                   ...                 ...   
402  Samsung                  6.70            12+64+12   
403   Xiaomi                  6.57            48+8+2+2   
404    Apple                  6.70            12+12+12   
405     Oppo                  6.40           48+13+8+2   
406  Samsung                  6.70             48+12+5   

     Battery Capacity (mAh)  Storage  RAM  Price($)  
0                      3095      128    6       999  
1                      5000      256   12      1199  
2                      4500      128    8       899  
3                      5020      128    6       279  
4                      4614      128    8       799  
..                      ...      ...  ...       ...  
402                    4300      128    8      1049  
403                    4160      128    6       349  
404                    3687      128    6      1099  
405                    4025      128    8       429  
406                    4500      128    6       649  

[407 rows x 7 columns]

In [ ]:

dataset.drop(['Camera (MP)'],axis=1,inplace=True)
dataset



Brand  Screen Size (inches)  Battery Capacity (mAh)  Storage  RAM  \
0      Apple                  6.10                    3095      128    6   
1    Samsung                  6.80                    5000      256   12   
2    OnePlus                  6.70                    4500      128    8   
3     Xiaomi                  6.67                    5020      128    6   
4     Google                  6.40                    4614      128    8   
..       ...                   ...                     ...      ...  ...   
402  Samsung                  6.70                    4300      128    8   
403   Xiaomi                  6.57                    4160      128    6   
404    Apple                  6.70                    3687      128    6   
405     Oppo                  6.40                    4025      128    8   
406  Samsung                  6.70                    4500      128    6   

     Price($)  
0         999  
1        1199  
2         899  
3         279  
4         799  
..        ...  
402      1049  
403       349  
404      1099  
405       429  
406       649  

[407 rows x 6 columns]

In [ ]:
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values
print(X)
print(Y)

[['Apple' 6.1 3095 128 6]
 ['Samsung' 6.8 5000 256 12]
 ['OnePlus' 6.7 4500 128 8]
 ...
 ['Apple' 6.7 3687 128 6]
 ['Oppo' 6.4 4025 128 8]
 ['Samsung' 6.7 4500 128 6]]
[ 999 1199  899  279  799  799  999  249  699 1199  329  449  329  699
 1199  329  799  199  299  379  179  279  249  729  279  599  139  299
  139  189  449  179  399  259  279  159  229  399  199  499  159  129
  189  399  529  699  369  199  159  179  189 1099  169   99  459  239
  199 1299  249  429  659  199  399  269  239  449  359  229  499  179
  169  239  329  369  599  799  139  799  799  399  699  329  399  999
  699  699  549 1299  999  899  399  449  319  269  349  269  279  249
  349  699  699  299  999  969 1199  149  139   99  699   99  199  169
  999  499  399  799  179  219  249  149  199  279  179  899  269  229
  399  239  149  279  329  149  549  449  279  199  399  179  399  109
  219  149  299  279  149  189  169  389 1199  299  219  299  149  249
  219  249  179  299  309  179  369  349  499  199 

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(sparse_output=False),[0])],remainder='passthrough')
X = np.array(ct.fit_transform(X))


In [ ]:
print(X)

[[1.0 0.0 0.0 ... 3095 128 6]
 [0.0 0.0 0.0 ... 5000 256 12]
 [0.0 0.0 0.0 ... 4500 128 8]
 ...
 [1.0 0.0 0.0 ... 3687 128 6]
 [0.0 0.0 0.0 ... 4025 128 8]
 [0.0 0.0 0.0 ... 4500 128 6]]


Linear Regression

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=1)
print(X_train)
print(X_test)

[[0.0 0.0 0.0 ... 5000 128 8]
 [0.0 0.0 0.0 ... 4300 128 8]
 [0.0 0.0 0.0 ... 4500 256 12]
 ...
 [1.0 0.0 0.0 ... 2942 128 3]
 [0.0 0.0 0.0 ... 6000 128 4]
 [0.0 0.0 0.0 ... 4500 128 8]]
[[0.0 0.0 0.0 ... 4300 256 8]
 [1.0 0.0 0.0 ... 1821 64 3]
 [0.0 0.0 0.0 ... 4500 128 6]
 ...
 [0.0 0.0 0.0 ... 4350 128 8]
 [0.0 0.0 0.0 ... 6000 128 6]
 [0.0 0.0 0.0 ... 4500 128 6]]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression()

In [ ]:
print('Test dataset Y value',Y_test)
Y_pred_lr = regressor.predict(X_test)
print("Predicted",Y_pred_lr)
print("X values",X_test)

Test dataset Y value [ 999  399  649  319  169 1099  549  199  189  279  349  139  189  699
  279  269 1049  799  279  159  329  249  109  149  199  139  189  129
  999  249  299  799  279  369  999  399  749  249  429  599  329  429
  249  279  449  199   99  549   99  149  199  399  229  299  149 1099
  299  279  329  179  349  149  449  229  749  729  139  179  379  229
  299  279  799 1399  449  699  449  799  349  129  349  329  449   99
  729  799  699  269  199  249  199  199  199  179 1399  249  699  249
  159  449  219  699]
Predicted [ 791.95062693  459.95062693  503.95062693  353.95062693  117.95062693
  981.95062693  687.95062693   87.95062693  109.95062693  281.95062693
  741.95062693   69.95062693  247.95062693  745.95062693  317.95062693
  435.95062693  635.95062693  773.95062693  289.95062693  109.95062693
  477.95062693  317.95062693  109.95062693   77.95062693  299.95062693
  129.95062693   89.95062693  -26.04937307  683.95062693  435.95062693
  441.95062693  745.9506

In [ ]:
from sklearn.metrics import mean_absolute_error , mean_squared_error , r2_score

lr_mae = mean_absolute_error(Y_test, Y_pred_lr)
lr_mse = mean_squared_error(Y_test, Y_pred_lr)
lr_r2 = r2_score(Y_test, Y_pred_lr)

print("\nLinear Regression:")
print("MAE:", lr_mae)
print("MSE:", lr_mse)
print("R-squared:", lr_r2)


Linear Regression:
MAE: 95.62164238411313
MSE: 15840.603519464259
R-squared: 0.8112263783135554


KNN

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
Regressor = KNeighborsRegressor()
Regressor.fit(X_train,Y_train)

KNeighborsRegressor()

In [ ]:
Y_pred_knn= Regressor.predict(X_test)
print(np.concatenate((Y_pred_knn.reshape(len(Y_pred_knn),1),Y_test.reshape(len(Y_test),1)),1))

[[1179.  999.]
 [ 529.  399.]
 [ 559.  649.]
 [ 279.  319.]
 [ 195.  169.]
 [ 909. 1099.]
 [ 503.  549.]
 [ 167.  199.]
 [ 161.  189.]
 [ 245.  279.]
 [ 511.  349.]
 [ 143.  139.]
 [ 165.  189.]
 [ 679.  699.]
 [ 239.  279.]
 [ 291.  269.]
 [ 477. 1049.]
 [ 709.  799.]
 [ 275.  279.]
 [ 161.  159.]
 [ 407.  329.]
 [ 193.  249.]
 [ 179.  109.]
 [ 143.  149.]
 [ 221.  199.]
 [ 169.  139.]
 [ 167.  189.]
 [ 115.  129.]
 [ 649.  999.]
 [ 291.  249.]
 [ 465.  299.]
 [ 679.  799.]
 [ 215.  279.]
 [ 301.  369.]
 [ 909.  999.]
 [ 469.  399.]
 [ 817.  749.]
 [ 265.  249.]
 [ 277.  429.]
 [ 591.  599.]
 [ 265.  329.]
 [ 391.  429.]
 [ 265.  249.]
 [ 263.  279.]
 [ 553.  449.]
 [ 185.  199.]
 [ 115.   99.]
 [ 459.  549.]
 [ 179.   99.]
 [ 169.  149.]
 [ 371.  199.]
 [ 529.  399.]
 [ 239.  229.]
 [ 465.  299.]
 [ 161.  149.]
 [ 889. 1099.]
 [ 245.  299.]
 [ 215.  279.]
 [ 393.  329.]
 [ 203.  179.]
 [ 365.  349.]
 [ 169.  149.]
 [ 519.  449.]
 [ 277.  229.]
 [ 591.  749.]
 [ 579.  729.]
 [ 153.  1

In [ ]:
knn_mae = mean_absolute_error(Y_test, Y_pred_knn)
knn_mse = mean_squared_error(Y_test, Y_pred_knn)
knn_r2 = r2_score(Y_test, Y_pred_knn)

print("\nK-Nearest Neighbors:")
print("MAE:", knn_mae)
print("MSE:", knn_mse)
print("R-squared:", knn_r2)


K-Nearest Neighbors:
MAE: 77.54901960784314
MSE: 13234.313725490196
R-squared: 0.8422857229255428


Random Forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#
rf_model = RandomForestRegressor(n_estimators=29, random_state=42)

rf_model.fit(X_train, Y_train)

Y_test_pred = rf_model.predict(X_test)

mse = mean_squared_error(Y_test, Y_test_pred)
mae = mean_absolute_error(Y_test, Y_test_pred)
r2 = r2_score(Y_test, Y_test_pred)

print("Mean Squared Error:", mse)
print("Mean Absolute Error:", mae)
print("R-squared:", r2)

Mean Squared Error: 22989.550282776763
Mean Absolute Error: 83.39119387674157
R-squared: 0.7260318609395273
